name: Django Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Run Tests
        run: |
          cd backend
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Vercel Deploy
        run: curl -X POST https://api.vercel.com/v1/integrations/deploy/QM_ENcrypted_TOKEN_Go_here
