name: CI/CD for Job Posting App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-directory-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List root directory (to confirm structure)
        run: |
          ls -al
          ls -al job-posting-backend || echo "job-posting-backend not found"
          ls -al job-posting-frontend || echo "job-posting-frontend not found"

  build-backend:
    runs-on: ubuntu-latest
    needs: check-directory-structure
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Django dependencies and Run Tests
        run: |
          cd job-portal-backend
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          python manage.py test

  build-frontend:
    runs-on: ubuntu-latest
    needs: check-directory-structure
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install and Build React App
        run: |
          cd job-portal-frontend
          npm install
          npm run build

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN
